// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: asset.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getAssetById = `-- name: GetAssetById :one
SELECT 
  a.id,
  a.owner,
  a.price,
  a.detail,
  a.status,
  a.created_at,
  a.updated_at,
  ac.id AS contact_id,
  ac.contact_name,
  ac.contact_detail,
  ai.id AS image_id,
  ai.image_url
FROM assets a
LEFT JOIN asset_contacts ac ON ac.asset_id = a.id
LEFT JOIN asset_images ai ON ai.asset_id = a.id
WHERE a.id = $1
`

type GetAssetByIdRow struct {
	ID            int64          `json:"id"`
	Owner         string         `json:"owner"`
	Price         int64          `json:"price"`
	Detail        string         `json:"detail"`
	Status        bool           `json:"status"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	ContactID     sql.NullInt64  `json:"contact_id"`
	ContactName   sql.NullString `json:"contact_name"`
	ContactDetail sql.NullString `json:"contact_detail"`
	ImageID       sql.NullInt64  `json:"image_id"`
	ImageUrl      sql.NullString `json:"image_url"`
}

func (q *Queries) GetAssetById(ctx context.Context, id int64) (GetAssetByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getAssetById, id)
	var i GetAssetByIdRow
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Price,
		&i.Detail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContactID,
		&i.ContactName,
		&i.ContactDetail,
		&i.ImageID,
		&i.ImageUrl,
	)
	return i, err
}

const getAssetsByUsername = `-- name: GetAssetsByUsername :many
SELECT 
  a.id,
  a.owner,
  a.price,
  a.detail,
  a.status,
  a.created_at,
  a.updated_at,
  ac.id AS contact_id,
  ac.contact_name,
  ac.contact_detail,
  ai.id AS image_id,
  ai.image_url
FROM assets a
LEFT JOIN asset_contacts ac ON ac.asset_id = a.id
LEFT JOIN asset_images ai ON ai.asset_id = a.id
WHERE a.owner = $1
`

type GetAssetsByUsernameRow struct {
	ID            int64          `json:"id"`
	Owner         string         `json:"owner"`
	Price         int64          `json:"price"`
	Detail        string         `json:"detail"`
	Status        bool           `json:"status"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	ContactID     sql.NullInt64  `json:"contact_id"`
	ContactName   sql.NullString `json:"contact_name"`
	ContactDetail sql.NullString `json:"contact_detail"`
	ImageID       sql.NullInt64  `json:"image_id"`
	ImageUrl      sql.NullString `json:"image_url"`
}

func (q *Queries) GetAssetsByUsername(ctx context.Context, owner string) ([]GetAssetsByUsernameRow, error) {
	rows, err := q.db.QueryContext(ctx, getAssetsByUsername, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAssetsByUsernameRow{}
	for rows.Next() {
		var i GetAssetsByUsernameRow
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Price,
			&i.Detail,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContactID,
			&i.ContactName,
			&i.ContactDetail,
			&i.ImageID,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAsset = `-- name: InsertAsset :one
INSERT INTO assets 
    (owner, price, detail)
VALUES 
    ($1, $2, $3)
RETURNING id, owner, price, detail, status, created_at, updated_at
`

type InsertAssetParams struct {
	Owner  string `json:"owner"`
	Price  int64  `json:"price"`
	Detail string `json:"detail"`
}

func (q *Queries) InsertAsset(ctx context.Context, arg InsertAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, insertAsset, arg.Owner, arg.Price, arg.Detail)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Price,
		&i.Detail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
