// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: asset_image.sql

package db

import (
	"context"
)

const insertAssetImage = `-- name: InsertAssetImage :one
INSERT INTO asset_images 
    (asset_id, image_url)
VALUES 
    ($1, $2)
RETURNING id, asset_id, image_url
`

type InsertAssetImageParams struct {
	AssetID  int64  `json:"asset_id"`
	ImageUrl string `json:"image_url"`
}

func (q *Queries) InsertAssetImage(ctx context.Context, arg InsertAssetImageParams) (AssetImage, error) {
	row := q.db.QueryRowContext(ctx, insertAssetImage, arg.AssetID, arg.ImageUrl)
	var i AssetImage
	err := row.Scan(&i.ID, &i.AssetID, &i.ImageUrl)
	return i, err
}
