// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Asset struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Price     int64     `json:"price"`
	Detail    string    `json:"detail"`
	Status    bool      `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type AssetContact struct {
	ID            int64     `json:"id"`
	AssetID       int64     `json:"asset_id"`
	ContactName   string    `json:"contact_name"`
	ContactDetail string    `json:"contact_detail"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type AssetImage struct {
	ID       int64  `json:"id"`
	AssetID  int64  `json:"asset_id"`
	ImageUrl string `json:"image_url"`
}

type User struct {
	Username   string         `json:"username"`
	Name       string         `json:"name"`
	Email      string         `json:"email"`
	Phone      string         `json:"phone"`
	Password   string         `json:"password"`
	ProfileUrl sql.NullString `json:"profile_url"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}
